apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: php-apache-hpa
    namespace: zad1
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: php-apache
    minReplicas: 1
    maxReplicas: 6
    targetCPUUtilizationPercentage: 50
